version: '2'

services:
  # this is our kafka cluster.
  kafka-cluster:
    image: landoop/fast-data-dev:latest
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker
    volumes:
      - ./kafka-connect-jdbc:/usr/share/java/kafka-connect-jdbc

  # This configuration allows you to start Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300

  # This configuration allows you to start Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  # This configuration allows you to start Postgres
  postgres:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: postgres     # define credentials
      POSTGRES_PASSWORD: postgres # define credentials
      POSTGRES_DB: postgres       # define database
    volumes:
      - ./postgres_users:/docker-entrypoint-initdb.d # create additional users
    ports:
      - 5432:5432                 # Postgres port

  # This configuration allows you to start MS SQL DB
  mssql:
    image: microsoft/mssql-server-linux:latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P4sw0rd123
    ports:
      - 1433:1433                 # MSSQL port

  # This configuration allows you to start My SQL DB
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql  # password for user root
    ports:
      - 3306:3306

  # This configuration allows you to start airflow
  airflow:
    image: puckel/docker-airflow:latest
    restart: always
    depends_on:
        - postgres
    volumes:
        - ./dags:/usr/local/airflow/dags
    ports:
        - 8080:8080               # airflow port
    command: webserver
